
session:
  key: u7pUYa_wj8ITfBmuo1Fwu_omiQHMsl8URQ6U750gjWE=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: postgres
  database: telegram
bot:
  name: asinc_t_bot
  username: asinc_t_bot
  token: 5226131452:AAHrKRcpvv-4s2Uzyvfxk4i65fvBCDj2JrQ



